language: ruby

rvm:
  - 1.9.3

gemfile:
  - Gemfile
  - spec/support/gemfiles/Gemfile.chef11

env:
  - RUBYOPT=W0

before_script:
  - ln -s chef-openvpn ../openvpn
  - cd spec/support/; librarian-chef install; cd ../..
